### PR TITLE
Add .NET (C#) example

### PR DESCRIPTION
**Pull request by usmanatron**
Added a new example based on .Net

### CODE REVIEW

**Comment by m1guelpf** [comment]
@usmanatron Looks good, but it needs to be tested before merging.
I can help you with the setup, it's really simple.
Also, if you tell me how to comply it or send me the binary pointing to activity.local.dev, I can test it.
Anyway, thank you for helping!

**Comment by usmanatron** [comment]
@m1guelpf Of course, totally understand.
I'm going to have a proper go and creating a dev environment tonight.  If I get stuck I'll let you know :-)

**Comment by m1guelpf** [comment]
@usmanatron Any updates on this?

**Comment by usmanatron** [comment]
Hi @m1guelpf 
Sorry, I haven't had a chance to have a go yet (it's getting busy at work).  Im still hoping to test imminently but might by on the weekend at this rate?
Thanks

**Comment by m1guelpf** [comment]
@usmanatron Just added installation instructions and Deploy to Heroku.

**Pull request merged**
